const sitemap = {
  // first level
  index: {
    id: 'index',
    route: '/',
    view: 'pages/index',
    parentRouteId: null,
    title: 'InYacht',
    menuItem: 'InYacht',
    children: [],
  },
  aboutUs: {
    id: 'aboutUs',
    route: '/o-nas',
    view: 'pages/about-us',
    parentRouteId: null,
    title: 'O nás',
    menuItem: 'O nás',
    children: [],
  },
  search: {
    id: 'search',
    route: '/vyhledavac',
    view: 'pages/search',
    parentRouteId: null,
    title: 'Vyhledávač',
    menuItem: 'Vyhledávač',
    children: [],
  },
  courses: {
    id: 'courses',
    route: '/kapitanske-kurzy',
    view: 'pages/courses',
    parentRouteId: null,
    title: 'Kapitánske kurzy',
    menuItem: 'Kapitánske kurzy',
    children: [],
  },
  contact: {
    id: 'contact',
    route: '/kontakt',
    view: 'pages/contact',
    parentRouteId: null,
    title: 'Kontakt',
    menuItem: 'Kontakt',
    children: [],
  },
  faq: {
    id: 'faq',
    route: '/faq',
    view: 'pages/yachting/faq',
    parentRouteId: 'yachting',
    title: 'Faq',
    menuItem: 'Námořní jachting',
    children: [],
  },
  news: {
    id: 'news',
    route: '/#novinky',
    view: 'pages/yachting/news',
    parentRouteId: 'yachting',
    title: 'Novinky',
    menuItem: 'Novinky',
    children: [],
  },
  newsPost: {
    id: 'newsPost',
    route: '/novinky/:newsPostSlug',
    view: 'pages/yachting/newsPost',
    parentRouteId: 'yachting',
    title: 'Novinky',
    // menuItem: 'Novinky',
    // children: [],
  },
  oops: {
    id: 'weather',
    view: 'pages/oops',
    title: 'Oops',
  }
};

module.exports = sitemap;
