import { ContentItem, Fields, IContentItem } from 'kentico-cloud-delivery-typescript-sdk';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' module.
 * You can substitute instances of 'IContentItem' with a model defined in other class
 * to get access to all properties. This is applicable only if you know what item type the field contains.
 */
export class FaqPage extends ContentItem {
    public title: Fields.TextField;
    public leadingParagraph: Fields.TextField;
    public text: Fields.RichTextField;
    public coverImage: Fields.AssetsField;
    public faqs: IContentItem[];
    
    constructor(){
        super({
            propertyResolver: ((fieldName: string) => {
                
                if (fieldName === 'leading_paragraph'){
                    return 'leadingParagraph';
                }

                if (fieldName === 'cover_image'){
                    return 'coverImage';
                }

                return fieldName;
            })
        })    
    }
    
}